### ISSUE TITLE
[Security] Workflow build.yml is using vulnerable action codecov/codecov-action

### ISSUE THREAD

**Issue by igibek** [sauravhiremath/ptransfer#17]
The workflow build.yml is referencing action codecov/codecov-action using references v1.1.1. However this reference is missing the commit [c6a36d2dbbf6a734e6ef75af344acdf122fcd9f9](https://github.com/codecov/codecov-action/commits/c6a36d2dbbf6a734e6ef75af344acdf122fcd9f9) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by sauravhiremath** [comment]
Thanks @igibek for pointing it out, `codecov-action` has been updated to v2 in lieu of the vulnerability
